# Generated by Django 6.0.5 on 2026-06-18 17:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0006_alter_category_slug_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='page',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
